/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Announcement {
  'active' : boolean,
  'text' : string,
  'eventDate' : bigint,
}
export interface MassTiming {
  'day' : string,
  'serviceType' : string,
  'time' : string,
}
export interface MediaItem {
  'url' : string,
  'caption' : string,
  'mediaType' : string,
}
export interface Prayer {
  'title' : string,
  'content' : string,
  'language' : string,
}
export interface SpiritualMessage {
  'title' : string,
  'date' : bigint,
  'fullText' : string,
  'author' : string,
}
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  'addMassTiming' : ActorMethod<[string, string, string], undefined>,
  'addMediaItem' : ActorMethod<[string, string, string], undefined>,
  'addPrayer' : ActorMethod<[string, string, string], undefined>,
  'countMassSchedule' : ActorMethod<[], bigint>,
  'countMediaGallery' : ActorMethod<[], bigint>,
  'countPrayers' : ActorMethod<[], bigint>,
  'filterPrayers' : ActorMethod<[string], Array<Prayer>>,
  'getAnnouncement' : ActorMethod<[], [] | [Announcement]>,
  'getMassSchedule' : ActorMethod<[], Array<MassTiming>>,
  'getMediaGallery' : ActorMethod<[], Array<MediaItem>>,
  'getPrayersByLanguage' : ActorMethod<[string], Array<Prayer>>,
  'getSpiritualMessage' : ActorMethod<[], [] | [SpiritualMessage]>,
  'updateAnnouncement' : ActorMethod<[string, bigint, boolean], undefined>,
  'updateSpiritualMessage' : ActorMethod<[string, string, string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];