/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const Prayer = IDL.Record({
  'title' : IDL.Text,
  'content' : IDL.Text,
  'language' : IDL.Text,
});
export const Announcement = IDL.Record({
  'active' : IDL.Bool,
  'text' : IDL.Text,
  'eventDate' : IDL.Int,
});
export const MassTiming = IDL.Record({
  'day' : IDL.Text,
  'serviceType' : IDL.Text,
  'time' : IDL.Text,
});
export const MediaItem = IDL.Record({
  'url' : IDL.Text,
  'caption' : IDL.Text,
  'mediaType' : IDL.Text,
});
export const SpiritualMessage = IDL.Record({
  'title' : IDL.Text,
  'date' : IDL.Int,
  'fullText' : IDL.Text,
  'author' : IDL.Text,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  'addMassTiming' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'addMediaItem' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'addPrayer' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'countMassSchedule' : IDL.Func([], [IDL.Nat], ['query']),
  'countMediaGallery' : IDL.Func([], [IDL.Nat], ['query']),
  'countPrayers' : IDL.Func([], [IDL.Nat], ['query']),
  'filterPrayers' : IDL.Func([IDL.Text], [IDL.Vec(Prayer)], ['query']),
  'getAnnouncement' : IDL.Func([], [IDL.Opt(Announcement)], ['query']),
  'getMassSchedule' : IDL.Func([], [IDL.Vec(MassTiming)], ['query']),
  'getMediaGallery' : IDL.Func([], [IDL.Vec(MediaItem)], ['query']),
  'getPrayersByLanguage' : IDL.Func([IDL.Text], [IDL.Vec(Prayer)], ['query']),
  'getSpiritualMessage' : IDL.Func([], [IDL.Opt(SpiritualMessage)], ['query']),
  'updateAnnouncement' : IDL.Func([IDL.Text, IDL.Int, IDL.Bool], [], []),
  'updateSpiritualMessage' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const Prayer = IDL.Record({
    'title' : IDL.Text,
    'content' : IDL.Text,
    'language' : IDL.Text,
  });
  const Announcement = IDL.Record({
    'active' : IDL.Bool,
    'text' : IDL.Text,
    'eventDate' : IDL.Int,
  });
  const MassTiming = IDL.Record({
    'day' : IDL.Text,
    'serviceType' : IDL.Text,
    'time' : IDL.Text,
  });
  const MediaItem = IDL.Record({
    'url' : IDL.Text,
    'caption' : IDL.Text,
    'mediaType' : IDL.Text,
  });
  const SpiritualMessage = IDL.Record({
    'title' : IDL.Text,
    'date' : IDL.Int,
    'fullText' : IDL.Text,
    'author' : IDL.Text,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    'addMassTiming' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'addMediaItem' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'addPrayer' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'countMassSchedule' : IDL.Func([], [IDL.Nat], ['query']),
    'countMediaGallery' : IDL.Func([], [IDL.Nat], ['query']),
    'countPrayers' : IDL.Func([], [IDL.Nat], ['query']),
    'filterPrayers' : IDL.Func([IDL.Text], [IDL.Vec(Prayer)], ['query']),
    'getAnnouncement' : IDL.Func([], [IDL.Opt(Announcement)], ['query']),
    'getMassSchedule' : IDL.Func([], [IDL.Vec(MassTiming)], ['query']),
    'getMediaGallery' : IDL.Func([], [IDL.Vec(MediaItem)], ['query']),
    'getPrayersByLanguage' : IDL.Func([IDL.Text], [IDL.Vec(Prayer)], ['query']),
    'getSpiritualMessage' : IDL.Func(
        [],
        [IDL.Opt(SpiritualMessage)],
        ['query'],
      ),
    'updateAnnouncement' : IDL.Func([IDL.Text, IDL.Int, IDL.Bool], [], []),
    'updateSpiritualMessage' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };